[package]
name = "rjsc"
version = "0.1.0"
authors = ["okno <paul.delafosse.etu@univ-lille.fr>"]
edition = "2018"
build = "build.rs"

[dependencies]
serde = "1.0.85"
serde_json = "1.0"
serde_derive = "1.0.85"
clap = "2.32"
cc = "1.0"